import {
  StepBackwardOutlined,
  StepForwardOutlined,
  FastBackwardOutlined,
  FastForwardOutlined,
  QuestionOutlined,
  PlusOutlined,
  QuestionCircleOutlined,
  PlusCircleOutlined,
  ShrinkOutlined,
  ArrowsAltOutlined,
  DownOutlined,
  LeftOutlined,
  RightOutlined,
  CaretUpOutlined,
  CaretDownOutlined,
  CaretLeftOutlined,
  CaretRightOutlined,
  UpCircleOutlined,
  DownCircleOutlined,
  LeftCircleOutlined,
  RightCircleOutlined,
  DoubleRightOutlined,
  DoubleLeftOutlined,
  VerticalLeftOutlined,
  VerticalAlignTopOutlined,
  VerticalRightOutlined,
  VerticalAlignMiddleOutlined,
  VerticalAlignBottomOutlined,
  ForwardOutlined,
  BackwardOutlined,
  RollbackOutlined,
  EnterOutlined,
  RetweetOutlined,
  SwapOutlined,
  SwapLeftOutlined,
  SwapRightOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  PlayCircleOutlined,
  UpSquareOutlined,
  LeftSquareOutlined,
  RightSquareOutlined,
  DownSquareOutlined,
  LoginOutlined,
  LogoutOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  BorderBottomOutlined,
  BorderHorizontalOutlined,
  BorderInnerOutlined,
  BorderOuterOutlined,
  BorderLeftOutlined,
  BorderRightOutlined,
  BorderTopOutlined,
  BorderVerticleOutlined,
  RadiusUpleftOutlined,
  PicCenterOutlined,
  PicLeftOutlined,
  PicRightOutlined,
  RadiusBottomleftOutlined,
  RadiusUprightOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  RadiusBottomrightOutlined,
  PauseOutlined,
  MinusOutlined,
  MinusCircleOutlined,
  PauseCircleOutlined,
  PlusSquareOutlined,
  InfoOutlined,
  ExclamationOutlined,
  MinusSquareOutlined,
  InfoCircleOutlined,
  CloseOutlined,
  ExclamationCircleOutlined,
  CloseCircleOutlined,
  CheckOutlined,
  CloseSquareOutlined,
  CheckSquareOutlined,
  CheckCircleOutlined,
  ClockCircleOutlined,
  IssuesCloseOutlined,
  WarningOutlined,
  StopOutlined,
  EditOutlined,
  FormOutlined,
  CopyOutlined,
  DeleteOutlined,
  ScissorOutlined,
  SnippetsOutlined,
  DiffOutlined,
  HighlightOutlined,
  AlignCenterOutlined,
  AlignLeftOutlined,
  AlignRightOutlined,
  BgColorsOutlined,
  BoldOutlined,
  ItalicOutlined,
  UnderlineOutlined,
  StrikethroughOutlined,
  RedoOutlined,
  UndoOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
  FontSizeOutlined,
  FontColorsOutlined,
  LineHeightOutlined,
  DashOutlined,
  AreaChartOutlined,
  PieChartOutlined,
  BarChartOutlined,
  DotChartOutlined,
  LineChartOutlined,
  RadarChartOutlined,
  HeatMapOutlined,
  FallOutlined,
  RiseOutlined,
  StockOutlined,
  BoxPlotOutlined,
  FundOutlined,
  SlidersOutlined,
  AccountBookOutlined,
  AimOutlined,
  AlertOutlined,
  ApartmentOutlined,
  ApiOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  AudioOutlined,
  AudioMutedOutlined,
  AuditOutlined,
  BankOutlined,
  BarcodeOutlined,
  BarsOutlined,
  BellOutlined,
  BlockOutlined,
  BookOutlined,
  BorderlessTableOutlined,
  BugOutlined,
  BuildOutlined,
  BranchesOutlined,
  BorderOutlined,
  BulbOutlined,
  CalendarOutlined,
  CalculatorOutlined,
  CameraOutlined,
  CarOutlined,
  CiCircleOutlined,
  CarryOutOutlined,
  CiOutlined,
  CloudDownloadOutlined,
  ClearOutlined,
  CloudOutlined,
  CloudSyncOutlined,
  CloudServerOutlined,
  ClusterOutlined,
  CloudUploadOutlined,
  CodeOutlined,
  CoffeeOutlined,
  CompassOutlined,
  CommentOutlined,
  CompressOutlined,
  ContactsOutlined,
  ConsoleSqlOutlined,
  ContainerOutlined,
  ControlOutlined,
  CreditCardOutlined,
  CopyrightOutlined,
  CrownOutlined,
  CustomerServiceOutlined,
  DatabaseOutlined,
  DashboardOutlined,
  DeleteRowOutlined,
  DeliveredProcedureOutlined,
  DeleteColumnOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DisconnectOutlined,
  DislikeOutlined,
  DingtalkOutlined,
  DollarCircleOutlined,
  DownloadOutlined,
  DollarOutlined,
  EllipsisOutlined,
  EuroCircleOutlined,
  EnvironmentOutlined,
  EuroOutlined,
  ExpandAltOutlined,
  ExceptionOutlined,
  ExpandOutlined,
  ExportOutlined,
  EyeOutlined,
  ExperimentOutlined,
  FieldNumberOutlined,
  EyeInvisibleOutlined,
  FieldStringOutlined,
  FieldTimeOutlined,
  FileAddOutlined,
  FileDoneOutlined,
  FileExcelOutlined,
  FileOutlined,
  FileExclamationOutlined,
  FileGifOutlined,
  FileImageOutlined,
  FileJpgOutlined,
  FileMarkdownOutlined,
  FilePdfOutlined,
  FilePptOutlined,
  FileProtectOutlined,
  FileSearchOutlined,
  FileSyncOutlined,
  FileTextOutlined,
  FileUnknownOutlined,
  FileWordOutlined,
  FileZipOutlined,
  FilterOutlined,
  FireOutlined,
  FlagOutlined,
  FolderAddOutlined,
  FolderOutlined,
  FolderOpenOutlined,
  FolderViewOutlined,
  ForkOutlined,
  FormatPainterOutlined,
  FrownOutlined,
  FunctionOutlined,
  FundProjectionScreenOutlined,
  FunnelPlotOutlined,
  FundViewOutlined,
  GatewayOutlined,
  GifOutlined,
  GlobalOutlined,
  GoldOutlined,
  GiftOutlined,
  GroupOutlined,
  HddOutlined,
  HeartOutlined,
  HomeOutlined,
  HistoryOutlined,
  HourglassOutlined,
  IdcardOutlined,
  InboxOutlined,
  ImportOutlined,
  InsertRowAboveOutlined,
  InsertRowBelowOutlined,
  InsertRowLeftOutlined,
  InsuranceOutlined,
  InsertRowRightOutlined,
  KeyOutlined,
  InteractionOutlined,
  LaptopOutlined,
  LikeOutlined,
  LineOutlined,
  LinkOutlined,
  LayoutOutlined,
  Loading3QuartersOutlined,
  LockOutlined,
  MacCommandOutlined,
  MailOutlined,
  ManOutlined,
  MehOutlined,
  MenuOutlined,
  MedicineBoxOutlined,
  FieldBinaryOutlined,
  MergeCellsOutlined,
  MessageOutlined,
  MobileOutlined,
  MoneyCollectOutlined,
  MonitorOutlined,
  MoreOutlined,
  NodeCollapseOutlined,
  NodeExpandOutlined,
  NodeIndexOutlined,
  NotificationOutlined,
  NumberOutlined,
  OneToOneOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PayCircleOutlined,
  PercentageOutlined,
  PhoneOutlined,
  PictureOutlined,
  PlaySquareOutlined,
  PoundCircleOutlined,
  PoundOutlined,
  PoweroffOutlined,
  PrinterOutlined,
  ProfileOutlined,
  ProjectOutlined,
  PropertySafetyOutlined,
  PullRequestOutlined,
  PushpinOutlined,
  QrcodeOutlined,
  ReadOutlined,
  ReconciliationOutlined,
  RedEnvelopeOutlined,
  ReloadOutlined,
  RestOutlined,
  RobotOutlined,
  RocketOutlined,
  RotateLeftOutlined,
  RotateRightOutlined,
  SafetyCertificateOutlined,
  SaveOutlined,
  SafetyOutlined,
  ScanOutlined,
  ScheduleOutlined,
  SearchOutlined,
  SecurityScanOutlined,
  SelectOutlined,
  SendOutlined,
  SettingOutlined,
  ShakeOutlined,
  ShareAltOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SisternodeOutlined,
  SkinOutlined,
  SolutionOutlined,
  SoundOutlined,
  SplitCellsOutlined,
  StarOutlined,
  SubnodeOutlined,
  SwitcherOutlined,
  SyncOutlined,
  TableOutlined,
  TabletOutlined,
  TagOutlined,
  TagsOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToTopOutlined,
  ToolOutlined,
  TrademarkCircleOutlined,
  TrademarkOutlined,
  TransactionOutlined,
  TrophyOutlined,
  TranslationOutlined,
  UngroupOutlined,
  UnlockOutlined,
  UploadOutlined,
  UsbOutlined,
  UserAddOutlined,
  UserDeleteOutlined,
  UserOutlined,
  UserSwitchOutlined,
  UsergroupDeleteOutlined,
  UsergroupAddOutlined,
  VerifiedOutlined,
  VideoCameraAddOutlined,
  VideoCameraOutlined,
  WalletOutlined,
  WhatsAppOutlined,
  WomanOutlined,
  WifiOutlined,
  AndroidOutlined,
  AppleOutlined,
  WindowsOutlined,
  IeOutlined,
  ChromeOutlined,
  GithubOutlined,
  AliwangwangOutlined,
  WeiboSquareOutlined,
  WeiboCircleOutlined,
  TaobaoCircleOutlined,
  Html5Outlined,
  WeiboOutlined,
  TwitterOutlined,
  WechatOutlined,
  YoutubeOutlined,
  AlipayCircleOutlined,
  TaobaoOutlined,
  SkypeOutlined,
  QqOutlined,
  MediumWorkmarkOutlined,
  GitlabOutlined,
  MediumOutlined,
  LinkedinOutlined,
  GooglePlusOutlined,
  DropboxOutlined,
  FacebookOutlined,
  CodepenOutlined,
  CodeSandboxOutlined,
  AmazonOutlined,
  GoogleOutlined,
  CodepenCircleOutlined,
  AlipayOutlined,
  AntDesignOutlined,
  AntCloudOutlined,
  AliyunOutlined,
  ZhihuOutlined,
  SlackOutlined,
  SlackSquareOutlined,
  BehanceOutlined,
  BehanceSquareOutlined,
  DribbbleSquareOutlined,
  InstagramOutlined,
  YuqueOutlined,
  AlibabaOutlined,
  YahooOutlined,
  RedditOutlined,
  SketchOutlined,
  DribbbleOutlined
} from "@ant-design/icons";
import SmileOutlined from "@ant-design/icons/SmileOutlined";

export default [
  {
    key: 'directional',
    tab: '方向性图标',
    icons: [
      {name: 'StepBackwardOutlined', component: <StepBackwardOutlined/>},
      {name: 'StepForwardOutlined', component: <StepForwardOutlined/>},
      {name: 'FastBackwardOutlined', component: <FastBackwardOutlined/>},
      {name: 'FastForwardOutlined', component: <FastForwardOutlined/>},
      {name: 'ShrinkOutlined', component: <ShrinkOutlined/>},
      {name: 'ArrowsAltOutlined', component: <ArrowsAltOutlined/>},
      {name: 'DownOutlined', component: <DownOutlined/>},
      {name: 'LeftOutlined', component: <LeftOutlined/>},
      {name: 'RightOutlined', component: <RightOutlined/>},
      {name: 'CaretUpOutlined', component: <CaretUpOutlined/>},
      {name: 'CaretDownOutlined', component: <CaretDownOutlined/>},
      {name: 'CaretLeftOutlined', component: <CaretLeftOutlined/>},
      {name: 'CaretRightOutlined', component: <CaretRightOutlined/>},
      {name: 'UpCircleOutlined', component: <UpCircleOutlined/>},
      {name: 'DownCircleOutlined', component: <DownCircleOutlined/>},
      {name: 'LeftCircleOutlined', component: <LeftCircleOutlined/>},
      {name: 'RightCircleOutlined', component: <RightCircleOutlined/>},
      {name: 'DoubleRightOutlined', component: <DoubleRightOutlined/>},
      {name: 'DoubleLeftOutlined', component: <DoubleLeftOutlined/>},
      {name: 'VerticalLeftOutlined', component: <VerticalLeftOutlined/>},
      {name: 'VerticalRightOutlined', component: <VerticalRightOutlined/>},
      {name: 'VerticalAlignTopOutlined', component: <VerticalAlignTopOutlined/>},
      {name: 'VerticalAlignMiddleOutlined', component: <VerticalAlignMiddleOutlined/>},
      {name: 'VerticalAlignBottomOutlined', component: <VerticalAlignBottomOutlined/>},
      {name: 'ForwardOutlined', component: <ForwardOutlined/>},
      {name: 'BackwardOutlined', component: <BackwardOutlined/>},
      {name: 'RollbackOutlined', component: <RollbackOutlined/>},
      {name: 'EnterOutlined', component: <EnterOutlined/>},
      {name: 'RetweetOutlined', component: <RetweetOutlined/>},
      {name: 'SwapOutlined', component: <SwapOutlined/>},
      {name: 'SwapLeftOutlined', component: <SwapLeftOutlined/>},
      {name: 'SwapRightOutlined', component: <SwapRightOutlined/>},
      {name: 'ArrowUpOutlined', component: <ArrowUpOutlined/>},
      {name: 'ArrowDownOutlined', component: <ArrowDownOutlined/>},
      {name: 'ArrowLeftOutlined', component: <ArrowLeftOutlined/>},
      {name: 'ArrowRightOutlined', component: <ArrowRightOutlined/>},
      {name: 'PlayCircleOutlined', component: <PlayCircleOutlined/>},
      {name: 'UpSquareOutlined', component: <UpSquareOutlined/>},
      {name: 'DownSquareOutlined', component: <DownSquareOutlined/>},
      {name: 'LeftSquareOutlined', component: <LeftSquareOutlined/>},
      {name: 'RightSquareOutlined', component: <RightSquareOutlined/>},
      {name: 'LoginOutlined', component: <LoginOutlined/>},
      {name: 'LogoutOutlined', component: <LogoutOutlined/>},
      {name: 'MenuFoldOutlined', component: <MenuFoldOutlined/>},
      {name: 'MenuUnfoldOutlined', component: <MenuUnfoldOutlined/>},
      {name: 'BorderBottomOutlined', component: <BorderBottomOutlined/>},
      {name: 'BorderHorizontalOutlined', component: <BorderHorizontalOutlined/>},
      {name: 'BorderInnerOutlined', component: <BorderInnerOutlined/>},
      {name: 'BorderOuterOutlined', component: <BorderOuterOutlined/>},
      {name: 'BorderLeftOutlined', component: <BorderLeftOutlined/>},
      {name: 'BorderRightOutlined', component: <BorderRightOutlined/>},
      {name: 'BorderTopOutlined', component: <BorderTopOutlined/>},
      {name: 'BorderVerticleOutlined', component: <BorderVerticleOutlined/>},
      {name: 'PicCenterOutlined', component: <PicCenterOutlined/>},
      {name: 'PicLeftOutlined', component: <PicLeftOutlined/>},
      {name: 'PicRightOutlined', component: <PicRightOutlined/>},
      {name: 'RadiusBottomleftOutlined', component: <RadiusBottomleftOutlined/>},
      {name: 'RadiusBottomingOutlined', component: <RadiusBottomrightOutlined/>},
      {name: 'RadiusUpleftOutlined', component: <RadiusUpleftOutlined/>},
      {name: 'RadiusUprightOutlined', component: <RadiusUprightOutlined/>},
      {name: 'FullscreenOutlined', component: <FullscreenOutlined/>},
      {name: 'FullscreenExitOutlined', component: <FullscreenExitOutlined/>},
    ]
  },
  {
    key: 'suggestion',
    tab: '提示建议性图标',
    icons: [
      {name: 'QuestionOutlined', component: <QuestionOutlined/>},
      {name: 'QuestionCircleOutlined', component: <QuestionCircleOutlined/>},
      {name: 'PlusOutlined', component: <PlusOutlined/>},
      {name: 'PlusCircleOutlined', component: <PlusCircleOutlined/>},
      {name: 'PauseOutlined', component: <PauseOutlined/>},
      {name: 'PauseCircleOutlined', component: <PauseCircleOutlined/>},
      {name: 'MinusOutlined', component: <MinusOutlined/>},
      {name: 'MinusCircleOutlined', component: <MinusCircleOutlined/>},
      {name: 'PlusSquareOutlined', component: <PlusSquareOutlined/>},
      {name: 'MinusSquareOutlined', component: <MinusSquareOutlined/>},
      {name: 'InfoOutlined', component: <InfoOutlined/>},
      {name: 'InfoCircleOutlined', component: <InfoCircleOutlined/>},
      {name: 'ExclamationOutlined', component: <ExclamationOutlined/>},
      {name: 'ExclamationCircleOutlined', component: <ExclamationCircleOutlined/>},
      {name: 'CloseOutlined', component: <CloseOutlined/>},
      {name: 'CloseCircleOutlined', component: <CloseCircleOutlined/>},
      {name: 'CloseSquareOutlined', component: <CloseSquareOutlined/>},
      {name: 'CheckOutlined', component: <CheckOutlined/>},
      {name: 'CheckCircleOutlined', component: <CheckCircleOutlined/>},
      {name: 'CheckSquareOutlined', component: <CheckSquareOutlined/>},
      {name: 'ClockCircleOutlined', component: <ClockCircleOutlined/>},
      {name: 'WarningOutlined', component: <WarningOutlined/>},
      {name: 'IssuesCloseOutlined', component: <IssuesCloseOutlined/>},
      {name: 'StopOutlined', component: <StopOutlined/>},
    ]
  },
  {
    key: 'edit',
    tab: '编辑类图标',
    icons: [
      {name: 'EditOutlined', component: <EditOutlined/>},
      {name: 'FormOutlined', component: <FormOutlined/>},
      {name: 'CopyOutlined', component: <CopyOutlined/>},
      {name: 'ScissorOutlined', component: <ScissorOutlined/>},
      {name: 'DeleteOutlined', component: <DeleteOutlined/>},
      {name: 'SnippetsOutlined', component: <SnippetsOutlined/>},
      {name: 'DiffOutlined', component: <DiffOutlined/>},
      {name: 'HighlightOutlined', component: <HighlightOutlined/>},
      {name: 'AlignCenterOutlined', component: <AlignCenterOutlined/>},
      {name: 'AlignLeftOutlined', component: <AlignLeftOutlined/>},
      {name: 'AlignRightOutlined', component: <AlignRightOutlined/>},
      {name: 'BgColorsOutlined', component: <BgColorsOutlined/>},
      {name: 'BoldOutlined', component: <BoldOutlined/>},
      {name: 'ItalicOutlined', component: <ItalicOutlined/>},
      {name: 'UnderlineOutlined', component: <UnderlineOutlined/>},
      {name: 'StrikethroughOutlined', component: <StrikethroughOutlined/>},
      {name: 'RedoOutlined', component: <RedoOutlined/>},
      {name: 'UndoOutlined', component: <UndoOutlined/>},
      {name: 'ZoomInOutlined', component: <ZoomInOutlined/>},
      {name: 'ZoomOutOutlined', component: <ZoomOutOutlined/>},
      {name: 'FontColorsOutlined', component: <FontColorsOutlined/>},
      {name: 'FontSizeOutlined', component: <FontSizeOutlined/>},
      {name: 'LineHeightOutlined', component: <LineHeightOutlined/>},
      {name: 'DashOutlined', component: <DashOutlined/>},
    ]
  },
  {
    key: 'data',
    tab: '数据类图标',
    icons: [
      {name: 'AreaChartOutlined', component: <AreaChartOutlined/>},
      {name: 'PieChartOutlined', component: <PieChartOutlined/>},
      {name: 'BarChartOutlined', component: <BarChartOutlined/>},
      {name: 'DotChartOutlined', component: <DotChartOutlined/>},
      {name: 'LineChartOutlined', component: <LineChartOutlined/>},
      {name: 'RadarChartOutlined', component: <RadarChartOutlined/>},
      {name: 'HeatMapOutlined', component: <HeatMapOutlined/>},
      {name: 'FallOutlined', component: <FallOutlined/>},
      {name: 'RiseOutlined', component: <RiseOutlined/>},
      {name: 'StockOutlined', component: <StockOutlined/>},
      {name: 'BoxPlotOutlined', component: <BoxPlotOutlined/>},
      {name: 'FundOutlined', component: <FundOutlined/>},
      {name: 'SlidersOutlined', component: <SlidersOutlined/>}
    ]
  },
  {
    key: 'logo',
    tab: '品牌和标识',
    icons: [
      {name: 'AndroidOutlined', component: <AndroidOutlined/>},
      {name: 'AppleOutlined', component: <AppleOutlined/>},
      {name: 'WindowsOutlined', component: <WindowsOutlined/>},
      {name: 'IeOutlined', component: <IeOutlined/>},
      {name: 'ChromeOutlined', component: <ChromeOutlined/>},
      {name: 'GithubOutlined', component: <GithubOutlined/>},
      {name: 'AliwangwangOutlined', component: <AliwangwangOutlined/>},
      {name: 'WeiboSquareOutlined', component: <WeiboSquareOutlined/>},
      {name: 'WeiboCircleOutlined', component: <WeiboCircleOutlined/>},
      {name: 'TaobaoCircleOutlined', component: <TaobaoCircleOutlined/>},
      {name: 'Html5Outlined', component: <Html5Outlined/>},
      {name: 'WeiboOutlined', component: <WeiboOutlined/>},
      {name: 'TwitterOutlined', component: <TwitterOutlined/>},
      {name: 'WechatOutlined', component: <WechatOutlined/>},
      {name: 'YoutubeOutlined', component: <YoutubeOutlined/>},
      {name: 'AlipayCircleOutlined', component: <AlipayCircleOutlined/>},
      {name: 'TaobaoOutlined', component: <TaobaoOutlined/>},
      {name: 'SkypeOutlined', component: <SkypeOutlined/>},
      {name: 'QqOutlined', component: <QqOutlined/>},
      {name: 'MediumWorkmarkOutlined', component: <MediumWorkmarkOutlined/>},
      {name: 'GitlabOutlined', component: <GitlabOutlined/>},
      {name: 'MediumOutlined', component: <MediumOutlined/>},
      {name: 'LinkedinOutlined', component: <LinkedinOutlined/>},
      {name: 'GooglePlusOutlined', component: <GooglePlusOutlined/>},
      {name: 'DropboxOutlined', component: <DropboxOutlined/>},
      {name: 'FacebookOutlined', component: <FacebookOutlined/>},
      {name: 'CodepenOutlined', component: <CodepenOutlined/>},
      {name: 'CodeSandboxOutlined', component: <CodeSandboxOutlined/>},
      {name: 'AmazonOutlined', component: <AmazonOutlined/>},
      {name: 'GoogleOutlined', component: <GoogleOutlined/>},
      {name: 'CodepenCircleOutlined', component: <CodepenCircleOutlined/>},
      {name: 'AlipayOutlined', component: <AlipayOutlined/>},
      {name: 'AntDesignOutlined', component: <AntDesignOutlined/>},
      {name: 'AntCloudOutlined', component: <AntCloudOutlined/>},
      {name: 'AliyunOutlined', component: <AliyunOutlined/>},
      {name: 'ZhihuOutlined', component: <ZhihuOutlined/>},
      {name: 'SlackOutlined', component: <SlackOutlined/>},
      {name: 'SlackSquareOutlined', component: <SlackSquareOutlined/>},
      {name: 'BehanceOutlined', component: <BehanceOutlined/>},
      {name: 'BehanceSquareOutlined', component: <BehanceSquareOutlined/>},
      {name: 'DribbbleOutlined', component: <DribbbleOutlined/>},
      {name: 'DribbbleSquareOutlined', component: <DribbbleSquareOutlined/>},
      {name: 'InstagramOutlined', component: <InstagramOutlined/>},
      {name: 'YuqueOutlined', component: <YuqueOutlined/>},
      {name: 'AlibabaOutlined', component: <AlibabaOutlined/>},
      {name: 'YahooOutlined', component: <YahooOutlined/>},
      {name: 'RedditOutlined', component: <RedditOutlined/>},
      {name: 'SketchOutlined', component: <SketchOutlined/>},
    ]
  },
  {
    key: 'web',
    tab: '网站通用图标',
    icons: [
      {name: 'AccountBookOutlined', component: <AccountBookOutlined/>},
      {name: 'AimOutlined', component: <AimOutlined/>},
      {name: 'AlertOutlined', component: <AlertOutlined/>},
      {name: 'ApartmentOutlined', component: <ApartmentOutlined/>},
      {name: 'ApiOutlined', component: <ApiOutlined/>},
      {name: 'AppstoreAddOutlined', component: <AppstoreAddOutlined/>},
      {name: 'AppstoreOutlined', component: <AppstoreOutlined/>},
      {name: 'AudioOutlined', component: <AudioOutlined/>},
      {name: 'AudioMutedOutlined', component: <AudioMutedOutlined/>},
      {name: 'AuditOutlined', component: <AuditOutlined/>},
      {name: 'BankOutlined', component: <BankOutlined/>},
      {name: 'BarcodeOutlined', component: <BarcodeOutlined/>},
      {name: 'BarsOutlined', component: <BarsOutlined/>},
      {name: 'BellOutlined', component: <BellOutlined/>},
      {name: 'BlockOutlined', component: <BlockOutlined/>},
      {name: 'BookOutlined', component: <BookOutlined/>},
      {name: 'BorderOutlined', component: <BorderOutlined/>},
      {name: 'BorderlessTableOutlined', component: <BorderlessTableOutlined/>},
      {name: 'BranchesOutlined', component: <BranchesOutlined/>},
      {name: 'BugOutlined', component: <BugOutlined/>},
      {name: 'BuildOutlined', component: <BuildOutlined/>},
      {name: 'BulbOutlined', component: <BulbOutlined/>},
      {name: 'CalculatorOutlined', component: <CalculatorOutlined/>},
      {name: 'CalendarOutlined', component: <CalendarOutlined/>},
      {name: 'CameraOutlined', component: <CameraOutlined/>},
      {name: 'CarOutlined', component: <CarOutlined/>},
      {name: 'CarryOutOutlined', component: <CarryOutOutlined/>},
      {name: 'CiCircleOutlined', component: <CiCircleOutlined/>},
      {name: 'RetweetOutlined', component: <RetweetOutlined/>},
      {name: 'CiOutlined', component: <CiOutlined/>},
      {name: 'ClearOutlined', component: <ClearOutlined/>},
      {name: 'CloudDownloadOutlined', component: <CloudDownloadOutlined/>},
      {name: 'CloudOutlined', component: <CloudOutlined/>},
      {name: 'CloudServerOutlined', component: <CloudServerOutlined/>},
      {name: 'CloudSyncOutlined', component: <CloudSyncOutlined/>},
      {name: 'CloudUploadOutlined', component: <CloudUploadOutlined/>},
      {name: 'ClusterOutlined', component: <ClusterOutlined/>},
      {name: 'CodeOutlined', component: <CodeOutlined/>},
      {name: 'CoffeeOutlined', component: <CoffeeOutlined/>},
      {name: 'CommentOutlined', component: <CommentOutlined/>},
      {name: 'CompassOutlined', component: <CompassOutlined/>},
      {name: 'CompressOutlined', component: <CompressOutlined/>},
      {name: 'ConsoleSqlOutlined', component: <ConsoleSqlOutlined/>},
      {name: 'ContactsOutlined', component: <ContactsOutlined/>},
      {name: 'ContainerOutlined', component: <ContainerOutlined/>},
      {name: 'ControlOutlined', component: <ControlOutlined/>},
      {name: 'CopyrightOutlined', component: <CopyrightOutlined/>},
      {name: 'CreditCardOutlined', component: <CreditCardOutlined/>},
      {name: 'CrownOutlined', component: <CrownOutlined/>},
      {name: 'CustomerServiceOutlined', component: <CustomerServiceOutlined/>},
      {name: 'DashboardOutlined', component: <DashboardOutlined/>},
      {name: 'DatabaseOutlined', component: <DatabaseOutlined/>},
      {name: 'DeleteColumnOutlined', component: <DeleteColumnOutlined/>},
      {name: 'DeleteRowOutlined', component: <DeleteRowOutlined/>},
      {name: 'DeliveredProcedureOutlined', component: <DeliveredProcedureOutlined/>},
      {name: 'DeploymentUnitOutlined', component: <DeploymentUnitOutlined/>},
      {name: 'DesktopOutlined', component: <DesktopOutlined/>},
      {name: 'DingtalkOutlined', component: <DingtalkOutlined/>},
      {name: 'DisconnectOutlined', component: <DisconnectOutlined/>},
      {name: 'DislikeOutlined', component: <DislikeOutlined/>},
      {name: 'DollarCircleOutlined', component: <DollarCircleOutlined/>},
      {name: 'DollarOutlined', component: <DollarOutlined/>},
      {name: 'DownloadOutlined', component: <DownloadOutlined/>},
      {name: 'EllipsisOutlined', component: <EllipsisOutlined/>},
      {name: 'EnvironmentOutlined', component: <EnvironmentOutlined/>},
      {name: 'EuroCircleOutlined', component: <EuroCircleOutlined/>},
      {name: 'EuroOutlined', component: <EuroOutlined/>},
      {name: 'ExceptionOutlined', component: <ExceptionOutlined/>},
      {name: 'ExpandAltOutlined', component: <ExpandAltOutlined/>},
      {name: 'ExpandOutlined', component: <ExpandOutlined/>},
      {name: 'ExperimentOutlined', component: <ExperimentOutlined/>},
      {name: 'ExportOutlined', component: <ExportOutlined/>},
      {name: 'EyeOutlined', component: <EyeOutlined/>},
      {name: 'EyeInvisibleOutlined', component: <EyeInvisibleOutlined/>},
      {name: 'FieldBinaryOutlined', component: <FieldBinaryOutlined/>},
      {name: 'FieldNumberOutlined', component: <FieldNumberOutlined/>},
      {name: 'FieldStringOutlined', component: <FieldStringOutlined/>},
      {name: 'FieldTimeOutlined', component: <FieldTimeOutlined/>},
      {name: 'FileAddOutlined', component: <FileAddOutlined/>},
      {name: 'FileDoneOutlined', component: <FileDoneOutlined/>},
      {name: 'FileExcelOutlined', component: <FileExcelOutlined/>},
      {name: 'FileExclamationOutlined', component: <FileExclamationOutlined/>},
      {name: 'FileOutlined', component: <FileOutlined/>},
      {name: 'FileGifOutlined', component: <FileGifOutlined/>},
      {name: 'FileImageOutlined', component: <FileImageOutlined/>},
      {name: 'FileJpgOutlined', component: <FileJpgOutlined/>},
      {name: 'FileMarkdownOutlined', component: <FileMarkdownOutlined/>},
      {name: 'FilePdfOutlined', component: <FilePdfOutlined/>},
      {name: 'FilePptOutlined', component: <FilePptOutlined/>},
      {name: 'FileProtectOutlined', component: <FileProtectOutlined/>},
      {name: 'FileSearchOutlined', component: <FileSearchOutlined/>},
      {name: 'FileSyncOutlined', component: <FileSyncOutlined/>},
      {name: 'FileTextOutlined', component: <FileTextOutlined/>},
      {name: 'FileUnknownOutlined', component: <FileUnknownOutlined/>},
      {name: 'FileWordOutlined', component: <FileWordOutlined/>},
      {name: 'FileZipOutlined', component: <FileZipOutlined/>},
      {name: 'FilterOutlined', component: <FilterOutlined/>},
      {name: 'FireOutlined', component: <FireOutlined/>},
      {name: 'FlagOutlined', component: <FlagOutlined/>},
      {name: 'FolderAddOutlined', component: <FolderAddOutlined/>},
      {name: 'FolderOutlined', component: <FolderOutlined/>},
      {name: 'FolderOpenOutlined', component: <FolderOpenOutlined/>},
      {name: 'FolderViewOutlined', component: <FolderViewOutlined/>},
      {name: 'ForkOutlined', component: <ForkOutlined/>},
      {name: 'FormatPainterOutlined', component: <FormatPainterOutlined/>},
      {name: 'FrownOutlined', component: <FrownOutlined/>},
      {name: 'FunctionOutlined', component: <FunctionOutlined/>},
      {name: 'FundProjectionScreenOutlined', component: <FundProjectionScreenOutlined/>},
      {name: 'FundViewOutlined', component: <FundViewOutlined/>},
      {name: 'FunnelPlotOutlined', component: <FunnelPlotOutlined/>},
      {name: 'GatewayOutlined', component: <GatewayOutlined/>},
      {name: 'GifOutlined', component: <GifOutlined/>},
      {name: 'GiftOutlined', component: <GiftOutlined/>},
      {name: 'GlobalOutlined', component: <GlobalOutlined/>},
      {name: 'GoldOutlined', component: <GoldOutlined/>},
      {name: 'GroupOutlined', component: <GroupOutlined/>},
      {name: 'HddOutlined', component: <HddOutlined/>},
      {name: 'HeartOutlined', component: <HeartOutlined/>},
      {name: 'HistoryOutlined', component: <HistoryOutlined/>},
      {name: 'HomeOutlined', component: <HomeOutlined/>},
      {name: 'HourglassOutlined', component: <HourglassOutlined/>},
      {name: 'IdcardOutlined', component: <IdcardOutlined/>},
      {name: 'ImportOutlined', component: <ImportOutlined/>},
      {name: 'InboxOutlined', component: <InboxOutlined/>},
      {name: 'InsertRowAboveOutlined', component: <InsertRowAboveOutlined/>},
      {name: 'InsertRowBelowOutlined', component: <InsertRowBelowOutlined/>},
      {name: 'InsertRowLeftOutlined', component: <InsertRowLeftOutlined/>},
      {name: 'InsertRowRightOutlined', component: <InsertRowRightOutlined/>},
      {name: 'InsuranceOutlined', component: <InsuranceOutlined/>},
      {name: 'InteractionOutlined', component: <InteractionOutlined/>},
      {name: 'KeyOutlined', component: <KeyOutlined/>},
      {name: 'LaptopOutlined', component: <LaptopOutlined/>},
      {name: 'LayoutOutlined', component: <LayoutOutlined/>},
      {name: 'LikeOutlined', component: <LikeOutlined/>},
      {name: 'LineOutlined', component: <LineOutlined/>},
      {name: 'LinkOutlined', component: <LinkOutlined/>},
      {name: 'Loading3QuartersOutlined', component: <Loading3QuartersOutlined/>},
      {name: 'LockOutlined', component: <LockOutlined/>},
      {name: 'MacCommandOutlined', component: <MacCommandOutlined/>},
      {name: 'MailOutlined', component: <MailOutlined/>},
      {name: 'ManOutlined', component: <ManOutlined/>},
      {name: 'MedicineBoxOutlined', component: <MedicineBoxOutlined/>},
      {name: 'MehOutlined', component: <MehOutlined/>},
      {name: 'MenuOutlined', component: <MenuOutlined/>},
      {name: 'MergeCellsOutlined', component: <MergeCellsOutlined/>},
      {name: 'MessageOutlined', component: <MessageOutlined/>},
      {name: 'MobileOutlined', component: <MobileOutlined/>},
      {name: 'MoneyCollectOutlined', component: <MoneyCollectOutlined/>},
      {name: 'MonitorOutlined', component: <MonitorOutlined/>},
      {name: 'MoreOutlined', component: <MoreOutlined/>},
      {name: 'NodeCollapseOutlined', component: <NodeCollapseOutlined/>},
      {name: 'NodeExpandOutlined', component: <NodeExpandOutlined/>},
      {name: 'NodeIndexOutlined', component: <NodeIndexOutlined/>},
      {name: 'NotificationOutlined', component: <NotificationOutlined/>},
      {name: 'NumberOutlined', component: <NumberOutlined/>},
      {name: 'OneToOneOutlined', component: <OneToOneOutlined/>},
      {name: 'PaperClipOutlined', component: <PaperClipOutlined/>},
      {name: 'PartitionOutlined', component: <PartitionOutlined/>},
      {name: 'PayCircleOutlined', component: <PayCircleOutlined/>},
      {name: 'PercentageOutlined', component: <PercentageOutlined/>},
      {name: 'PhoneOutlined', component: <PhoneOutlined/>},
      {name: 'PictureOutlined', component: <PictureOutlined/>},
      {name: 'PlaySquareOutlined', component: <PlaySquareOutlined/>},
      {name: 'PoundCircleOutlined', component: <PoundCircleOutlined/>},
      {name: 'PoundOutlined', component: <PoundOutlined/>},
      {name: 'PoweroffOutlined', component: <PoweroffOutlined/>},
      {name: 'PrinterOutlined', component: <PrinterOutlined/>},
      {name: 'ProfileOutlined', component: <ProfileOutlined/>},
      {name: 'ProjectOutlined', component: <ProjectOutlined/>},
      {name: 'PropertySafetyOutlined', component: <PropertySafetyOutlined/>},
      {name: 'PullRequestOutlined', component: <PullRequestOutlined/>},
      {name: 'PushpinOutlined', component: <PushpinOutlined/>},
      {name: 'QrcodeOutlined', component: <QrcodeOutlined/>},
      {name: 'ReadOutlined', component: <ReadOutlined/>},
      {name: 'ReconciliationOutlined', component: <ReconciliationOutlined/>},
      {name: 'RedEnvelopeOutlined', component: <RedEnvelopeOutlined/>},
      {name: 'ReloadOutlined', component: <ReloadOutlined/>},
      {name: 'RestOutlined', component: <RestOutlined/>},
      {name: 'RobotOutlined', component: <RobotOutlined/>},
      {name: 'RocketOutlined', component: <RocketOutlined/>},
      {name: 'RotateLeftOutlined', component: <RotateLeftOutlined/>},
      {name: 'RotateRightOutlined', component: <RotateRightOutlined/>},
      {name: 'SafetyCertificateOutlined', component: <SafetyCertificateOutlined/>},
      {name: 'SafetyOutlined', component: <SafetyOutlined/>},
      {name: 'SaveOutlined', component: <SaveOutlined/>},
      {name: 'ScanOutlined', component: <ScanOutlined/>},
      {name: 'ScheduleOutlined', component: <ScheduleOutlined/>},
      {name: 'SearchOutlined', component: <SearchOutlined/>},
      {name: 'SecurityScanOutlined', component: <SecurityScanOutlined/>},
      {name: 'SelectOutlined', component: <SelectOutlined/>},
      {name: 'SendOutlined', component: <SendOutlined/>},
      {name: 'SettingOutlined', component: <SettingOutlined/>},
      {name: 'ShakeOutlined', component: <ShakeOutlined/>},
      {name: 'ShareAltOutlined', component: <ShareAltOutlined/>},
      {name: 'ShopOutlined', component: <ShopOutlined/>},
      {name: 'ShoppingCartOutlined', component: <ShoppingCartOutlined/>},
      {name: 'ShoppingOutlined', component: <ShoppingOutlined/>},
      {name: 'SisternodeOutlined', component: <SisternodeOutlined/>},
      {name: 'SkinOutlined', component: <SkinOutlined/>},
      {name: 'SmileOutlined', component: <SmileOutlined/>},
      {name: 'SolutionOutlined', component: <SolutionOutlined/>},
      {name: 'SoundOutlined', component: <SoundOutlined/>},
      {name: 'SplitCellsOutlined', component: <SplitCellsOutlined/>},
      {name: 'StarOutlined', component: <StarOutlined/>},
      {name: 'SubnodeOutlined', component: <SubnodeOutlined/>},
      {name: 'SwitcherOutlined', component: <SwitcherOutlined/>},
      {name: 'SyncOutlined', component: <SyncOutlined/>},
      {name: 'TableOutlined', component: <TableOutlined/>},
      {name: 'TabletOutlined', component: <TabletOutlined/>},
      {name: 'TagOutlined', component: <TagOutlined/>},
      {name: 'TagsOutlined', component: <TagsOutlined/>},
      {name: 'TeamOutlined', component: <TeamOutlined/>},
      {name: 'ThunderboltOutlined', component: <ThunderboltOutlined/>},
      {name: 'ToTopOutlined', component: <ToTopOutlined/>},
      {name: 'ToolOutlined', component: <ToolOutlined/>},
      {name: 'TrademarkCircleOutlined', component: <TrademarkCircleOutlined/>},
      {name: 'TrademarkOutlined', component: <TrademarkOutlined/>},
      {name: 'TransactionOutlined', component: <TransactionOutlined/>},
      {name: 'TranslationOutlined', component: <TranslationOutlined/>},
      {name: 'TrophyOutlined', component: <TrophyOutlined/>},
      {name: 'UngroupOutlined', component: <UngroupOutlined/>},
      {name: 'UnlockOutlined', component: <UnlockOutlined/>},
      {name: 'UploadOutlined', component: <UploadOutlined/>},
      {name: 'UsbOutlined', component: <UsbOutlined/>},
      {name: 'UserAddOutlined', component: <UserAddOutlined/>},
      {name: 'UserDeleteOutlined', component: <UserDeleteOutlined/>},
      {name: 'UserOutlined', component: <UserOutlined/>},
      {name: 'UserSwitchOutlined', component: <UserSwitchOutlined/>},
      {name: 'UsergroupAddOutlined', component: <UsergroupAddOutlined/>},
      {name: 'UsergroupDeleteOutlined', component: <UsergroupDeleteOutlined/>},
      {name: 'VerifiedOutlined', component: <VerifiedOutlined/>},
      {name: 'VideoCameraAddOutlined', component: <VideoCameraAddOutlined/>},
      {name: 'VideoCameraOutlined', component: <VideoCameraOutlined/>},
      {name: 'WalletOutlined', component: <WalletOutlined/>},
      {name: 'WhatsAppOutlined', component: <WhatsAppOutlined/>},
      {name: 'WifiOutlined', component: <WifiOutlined/>},
      {name: 'WomanOutlined', component: <WomanOutlined/>},
    ]
  },
]
